### PR TITLE
Prepare for collab

### PR DESCRIPTION
**Pull request by kawazoe**
This PR tries to make it as easy as possible for multiple people to collaborate on this project, no matter their IDE or operating system. Ideally, this should be done with a linter like eslint, but that's a lot of work compared to a few setting files. The goal is that following PRs won't introduce random style changes that would make their review more difficult, and to reduce the need to think about style while making broad changes.

In no particular order:

- Fix a bad merge that duplicated a definition in `background.js`
- Add a `.editorconfig` file that attempts to match existing project styling as much as possible
- Auto-format all the code to match the `.editorconfig` style [1][2][3]
- Add a `.gitattributes` file to convert line endings on checkout between CRLF and LF for people on Windows vs Linux/macOS
- Add some WebStorm specific configs for typings and git configs [4]

[1] If you want something different, now is the best moment for a change.
[2] HTML and JSON files are the most impacted.
[3] Some of those settings are only supported by WebStorm, but there might be equivalents for other IDEs like vscode.
[4] Those are handled differently for each IDE so unfortunately there is no standard way of achieving this.

### CODE REVIEW

**Comment by kawazoe** [comment]
Last preparation PR! From here, it's only going to be v2 to v3 migration changes.

**Comment by kawazoe** [comment]
Hi @ish- ! I know it's been a while, but if you could merge this change, I have a new branch ready with a ton of changes for the switch to MV3.

**Comment by ish-** [comment]
@kawazoe thank you! I will deal with it soon :)

**Comment by kawazoe** [comment]
@ish- I think the v3 branch is ready to PR. I can either close this PR and reopen a new one with all of the stuff, or you can merge this one and then I'll PR from there. Your choice!

**Pull request merged**
